### ISSUE TITLE
NewtonSoft problem

### ISSUE THREAD

**Issue by jaimestuardo** [jgiacomini/TinyHttp#127]
Hello... when using Tiny.RestClient I always have problems with Newtonsoft dependency.

this error occurs:

No se puede cargar el archivo o ensamblado 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' ni una de sus dependencias. La definición del manifiesto del ensamblado no coincide con la referencia al ensamblado. (Excepción de HRESULT: 0x80131040)

 I have Newtonsoft 13. How can I make Tiny.RestClient to use this version? It insists to use version 11.

Than
Jaime

**Comment by jgiacomini** [comment]
Hello @jaimestuardo  on which .NET version do you use ?
